---
title: "Analyzing Simulated Model Selection"
author: "Jonathan Che"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
if(system("whoami", intern=TRUE) %in% c("rudeboybert", "aykim")){
  knitr::opts_knit$set(root.dir = "~/Documents/Projects/TreeCompetition/")
} else {
  knitr::opts_knit$set(root.dir = "~/TreeCompetition")
}
require(tidyverse)
require(knitr)
require(kableExtra)

# Discrete scales for color and linetype
cc <- scales::seq_gradient_pal("blue", "orange", "Lab")(seq(0,1,length.out=5))
cl <- c("solid", "longdash", "dashed", "dotted")
```

## Setup

```{r, include=FALSE}
sims_FF <- read_csv("Results/selection/sim-spvars-FALSE_spnoise-FALSE_100x100-500_cv4x4-k10-buffer10_seed1.csv")
sims_FT <- read_csv("Results/selection/sim-spvars-FALSE_spnoise-TRUE_100x100-500_cv4x4-k10-buffer10_seed1.csv")
sims_TF <- read_csv("Results/selection/sim-spvars-TRUE_spnoise-FALSE_100x100-500_cv4x4-k10-buffer10_seed1.csv")
sims_TT <- read_csv("Results/selection/sim-spvars-TRUE_spnoise-TRUE_100x100-500_cv4x4-k10-buffer10_seed1.csv")
```

## Analysis

```{r, echo=FALSE}
# Summary table for means
order_vec <- c("sel_train", "sel_cv", "sel_cv_flip", "sel_loo", "sel_grid", "sel_grid_flip", "sel_sloo")

sims_FF %>%
  gather(`Selection Method`, model_selected, sel_train:sel_sloo) %>%
  group_by(`Selection Method`) %>%
  summarize(
    `Underfit` = sum(model_selected<=3),
    `Correct` = sum(model_selected==4),
    `Overfit` = sum(model_selected>=5)) %>%
  slice(match(order_vec, `Selection Method`))

sims_TT %>%
  gather(`Selection Method`, model_selected, sel_train:sel_sloo) %>%
  group_by(`Selection Method`) %>%
  summarize(
    `Underfit` = sum(model_selected<=3),
    `Correct` = sum(model_selected==4),
    `Overfit` = sum(model_selected>=5)) %>%
  slice(match(order_vec, `Selection Method`))
```

pretty table below

```{r, echo=FALSE}
# Summary table for means
order_vec <- c("sel_train", "sel_cv", "sel_cv_flip", "sel_loo", "sel_grid", "sel_grid_flip", "sel_sloo")
sims_FF %>%
  gather(`Selection Method`, model_selected, sel_train:sel_sloo) %>%
  group_by(`Selection Method`) %>%
  summarize(
    `Selected $m_1$` = sum(model_selected==1),
    `Selected $m_2$` = sum(model_selected==2),
    `Selected $m_3$` = sum(model_selected==3),
    `Selected $m_4$` = sum(model_selected==4),
    `Selected $m_5$` = sum(model_selected==5),
    `Selected $m_6$` = sum(model_selected==6),
    `Selected $m_7$` = sum(model_selected==7)) %>%
  slice(match(order_vec, `Selection Method`)) %>%   # reorder rows
  kable(format = "latex", booktabs = T) %>%
  kable_styling(latex_options = "striped")
```

We see that buffered grid CV is the best at picking the correct model (model 3). While flipped K-fold CV outperforms regular K-fold CV, flipped buffered grid CV does not outperform buffered grid CV.

## Conclusion

Spatial CV methods are better at model selection!
